### ISSUE TITLE
Crash using with HIpChat

### ISSUE THREAD

**Issue by lacombar** [cdidier/irssi-xmpp#10]
I've been getting a few crashes using `irssi-xmpp` on HipChat XMPP bridges. I'll post more information when I'll have reproduced.

Version involved: irssi-xmpp-0.52-7 (on Fedora 23)

**Comment by cdidier** [comment]
Try building irssi-xmpp from this git repo, there are a few crashes that have been fixed since 0.52.

**Comment by lacombar** [comment]
the one I'm seeking is:

```
0x00007ffff56e193a in __strcmp_sse2_unaligned () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff56e193a in __strcmp_sse2_unaligned () from /lib64/libc.so.6
#1  0x00007ffff65914ca in g_slist_sort_real () from /lib64/libglib-2.0.so.0
#2  0x00007ffff3b8d061 in sig_recv_presence () from /usr/lib64/irssi/modules/libxmpp_core.so
#3  0x00005555555f2f62 in signal_emit_real ()
#4  0x00005555555f34cd in signal_emit ()
#5  0x00007ffff3b8e253 in handle_stanza () from /usr/lib64/irssi/modules/libxmpp_core.so
#6  0x00007ffff396fedf in connection_message_queue_cb () from /lib64/libloudmouth-1.so.0
#7  0x00007ffff39711c7 in message_queue_dispatch_func () from /lib64/libloudmouth-1.so.0
#8  0x00007ffff6573e3a in g_main_context_dispatch () from /lib64/libglib-2.0.so.0
#9  0x00007ffff65741d0 in g_main_context_iterate.isra () from /lib64/libglib-2.0.so.0
#10 0x00007ffff657427c in g_main_context_iteration () from /lib64/libglib-2.0.so.0
#11 0x0000555555574d76 in main ()
(gdb)
```

I'll give a try to `master`.

**Comment by cdidier** [comment]
Yes, try master. 2b8c2a30ef52e871a6af7f0498b505851d5b5289 should fix this.
